name: 'vanagon_mend_scan_action'
description: 'Scans vanagon builds for ruby dependencies and untrusted repos'
inputs:
  mendApiKey:
    description: 'mend API key'
    required: true
  mendToken:
    description: 'mend user token'
    required: true
  mendURL:
    description: 'mend URL for your mend endpoint'
    required: true
  productName:
    description: 'name of the product to send results to'
    required: true
  projectName:
    description: 'name of the project. Note that the branch, project, and platform will be appended'
    required: true
  branch:
    description: 'branch name to prepend to the snyk project name'
    required: false
  skipProjects:
    description: 'A comma separated list of projects to skip'
    required: false
  skipPlatforms:
    description: 'A comma separated list of platforms to skip'
    required: false
  sshKey:
    description: 'a base64 encoded SSH key to install on the container'
    required: false
  sshKeyName:
    description: 'Name of the SSH key. Written to /root/.ssh/<sshKeyName>'
    required: false
  svDebug:
    description: 'turn on debug logging'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
